tcms/models.py
# -*- coding: utf-8 -*-
from urlparse import urljoin
from xml.etree import ElementTree
from operator import or_

from django.db import models, transaction
from django.db.models.query import Q
from django.conf import settings
from django.utils.xmlutils import SimplerXMLGenerator
from django.utils.safestring import mark_safe
from django.utils.importlib import import_module
from django.core.exceptions import ValidationError

from tcms.data_types import BASE_TYPES
from tcms.tpl import PAGES, RENDER_EXTRA_CONTEXT
from tcms.utils import save_b64_image, image_to_b64, update_cache, \
                       normalize_path, dotted_dict_to_choices


# page states
WIP, LIVE, OLD = ('wip', 'live', 'old')
STATES = ((WIP, 'Work in Progress'), (LIVE, 'Live'), (OLD, 'Old page'))

# Load extra data types
EXTRA_TYPES_SETTINGS = getattr(settings, 'EXTRA_TYPES_SETTINGS', None)
if EXTRA_TYPES_SETTINGS:
    try:
        module, name = EXTRA_TYPES_SETTINGS.rsplit('.', 1)
        LOCAL_TYPES = getattr(import_module(module), name, [])
    except (AttributeError, ImportError):
        LOCAL_TYPES = []
else:
    LOCAL_TYPES = []

TYPES_MAP = dict((Type.__name__.lower(), Type)
                    for Type in BASE_TYPES + LOCAL_TYPES)

CMSID = 'cmsid'
IMAGES_UPLOAD_TO = getattr(settings, 'TCMS_IMAGES_UPLOAD_TO',
                           'cms/image/%Y/%m/%d')


class Path(models.Model):
    """A CMS Page path."""
    path = models.CharField(max_length=200)
    locale = models.CharField(max_length=255, blank=True, default='',
                              choices=settings.LANGUAGES)

    def save(self, *args, **kwargs):
        """Save method. Enforces absolute paths."""
        self.path = normalize_path(self.path)
        super(Path, self).save(*args, **kwargs)

    def full_url(self):
        """Returns path full url"""
        return urljoin(settings.SITE_URL, self.path)

    def live(self):
        """Returns current live Page for current instance path and
        locale values."""
        try:
            return self.pages.get(state=LIVE)
        except Page.DoesNotExist:
            pass

    def __unicode__(self):
        return self.path

    def __str__(self):
        return self.path

    class Meta:
        unique_together = ('path', 'locale')
        verbose_name = 'URL'


class Page(models.Model):
    """A CMS Page"""
    path = models.ForeignKey(Path, related_name='pages', verbose_name='URL')
    template = models.CharField(max_length=512,
                                choices=dotted_dict_to_choices(PAGES))
    state = models.CharField(max_length=20, default=WIP, choices=STATES)
    description = models.TextField(blank=True)
    updated = models.DateTimeField(editable=False, auto_now_add=True)

    # metadata
    meta_title = models.CharField(max_length=1024, blank=True, default='',
                                  help_text='Metadata title content')
    meta_description = models.CharField(max_length=1024, blank=True, default='',
                                    help_text='Metadata description content')
    meta_keywords = models.CharField(max_length=1024, blank=True, default='',
                                     help_text='Metadata keywords content')

    # values for search indexers
    search_image = models.ImageField(upload_to=IMAGES_UPLOAD_TO, blank=True,
                                     help_text='Image shown on search results')
    search_text = models.TextField(blank=True, default='',
                           help_text='Description displayed on search results')

    def __init__(self, *args, **kwargs):
        super(Page, self).__init__(*args, **kwargs)
        self._loaded = False
        self._rendered = False
        self._template = None

    @property
    def thumbnail(self):
        """Return @search_image as page thumbnail if it's needed to be included
        it's usually used on sharing sites like facebook"""
        return self.search_image

    def save(self, *args, **kwargs):
        """Save handler, will ensure that only one WIP exists per path"""
        if not self.id:
            Page.validate_unique_wip(self.path)
        super(Page, self).save(*args, **kwargs)

    @classmethod
    def validate_unique_wip(cls, path):
        """Validates WIP state uniqueness for path @path"""
        if Page.objects.filter(path=path, state=WIP).count() > 0:
            raise ValidationError(
                    'Another "Work in progress" page exist for given URL')

    @property
    def preview_url(self):
        return '%s?%s=%s&cms_locale=%s' % (self.path.path, CMSID, self.pk,
                                           self.path.locale)

    @property
    def tpl(self):
        """Returns Template Page instance for current defined template"""
        if self._template is None:
            self._template = PAGES.get(self.template)()
        return self._template

    def load(self, sections=None, rendered=False):
        """
        Load page data.
            If @section is passed, only data for that section is loaded.
            If @rendered flag is passed, only rendered data is loaded
        """
        if not self._loaded:
            if sections:
                if not isinstance(sections, (list, tuple)):
                    sections = (sections,)
                sections = reduce(or_, (Q(name__startswith=section)
                                            for section in sections))

            self._rendered = rendered
            if rendered: # load rendered content
                qs = self.rendered_data.values_list('name', 'value')
                if sections:
                    qs = qs.filter(sections)
                for name, value in qs:
                    setattr(self, name, mark_safe(value))
            else: # load values
                qs = self.values.values_list('name', 'value')
                if sections:
                    qs = qs.filter(sections)
                self.tpl.load(qs)
            self._loaded = True

    @property
    def is_live(self):
        """Return True if page is in Live state or False in other case"""
        return self.state == LIVE

    def refresh(self, *args, **kwargs):
        """Refresh rendered data, subsections are rendered by page template
        sections and stored. Extra arguments will be passed to section
        rendering method.
        """
        extra_context = kwargs.pop('extra_context', {})

        if RENDER_EXTRA_CONTEXT:
            extra_context.update(RENDER_EXTRA_CONTEXT)

        extra_context['cms'] = self
        kwargs['extra_context'] = extra_context

        self.load()
        for name, value in self.tpl.render_sections(*args, **kwargs):
            obj, created = Rendered.objects.get_or_create(page=self, name=name)
            obj.value = value
            obj.save()

    @transaction.commit_on_success
    def publish(self, *args, **kwargs):
        """Publish page, will generate rendered content and unpublish current
        live page with same path and state.

        Arguments will be passed to refresh method which will be passed to
        rendering method.
        """
        similar = {'path': self.path, 'state': LIVE}
        for page in Page.objects.filter(**similar):
            page.unpublish()

        self.refresh(*args, **kwargs)
        self.state = LIVE
        self.save()
        update_cache()

    def unpublish(self):
        """Unpublish page, rendered content is not droped"""
        self.state = OLD
        self.save()
        update_cache()

    @transaction.commit_on_success
    def delete(self):
        """Delete a Page, only no Live pages can be deleted. Rendered content
        and values are deleted too"""
        if self.state == LIVE:
            raise TypeError('live pages cannot be deleted')
        self.rendered_data.all().delete()
        self.values.all().delete()
        super(Page, self).delete()
        update_cache()

    @transaction.commit_on_success
    def copy(self, path):
        """Return copy of this page.

        Copies current page under a new @path. This method behaves like
        cloning if path is the same as current one.
        """
        args = {'path': path,
                'template': self.template,
                'description': self.description,
                'meta_title': self.meta_title,
                'meta_description': self.meta_description,
                'meta_keywords': self.meta_keywords,
                'search_image': self.search_image,
                'search_text': self.search_text}
        copy = Page(**args)
        copy.save()

        # duplicate values
        for value in self.values.all():
            value.id = None
            copy.values.add(value)

        return copy

    def to_xml(self, out, encoding=settings.DEFAULT_CHARSET):
        """Exports page data in a XML formated file. It stores
        page info as first item and value data following it.
        Files are base64 encoded and exported too.

        Example:
        <cms-page>
          <page path="/path/" template="homepage" description="Homepage"
                locale="en-gb" meta_title="Title" meta_description="Description"
                meta_keywords="Keywords" search_image="base64 encoded image"
                search_image_name="file name of search image"
                search_text="Search text"></page>
          <value name="heading" type="text" value="Page title"></value>
          <value name="an_image" type="image" value="bas64 enconded"></value>
          ...
        </cms-page>
        """
        xml = SimplerXMLGenerator(out=out, encoding=encoding)
        xml.startDocument()
        xml.startElement('cms-page', {})

        # store page info in first child
        data = {'path': self.path.path, 'template': self.template,
                'description': self.description, 'locale': self.path.locale,
                'meta_title': self.meta_title,
                'meta_description': self.meta_description,

tcms/templates/cms/cms_base.html
{% extends "admin/base_site.html" %}

{% block title %}tCMS | {{ _('Site admin') }} | {% block extra_title %}{% endblock %}{% endblock %}

{% block branding %}
<h1 id="site-name">{{ _('CMS administration') }}</h1>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="/admin/">Home</a>
  &rsaquo; <a href="/admin/tcms/">{{ _('Cms') }}</a>
  &rsaquo; <a href="/admin/tcms/page/">{{ _('Pages') }}</a>
  {% block extra_breadcrumbs %}{% endblock %}
</div>
{% endblock %}

tcms/templates/cms/copy.html
{% extends "cms/cms_base.html" %}
{% load adminmedia static %}

{% block extra_title %}Copy page{% endblock %}

{% block extrastyle %}
<link href="{% admin_media_prefix %}css/forms.css" rel="stylesheet" type="text/css" media="all" />
<link href="{% get_static_prefix %}css/cms.css" rel="stylesheet" type="text/css" media="all" />
{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{% admin_media_prefix %}js/admin/RelatedObjectLookups.js"></script>
{% endblock %}

{% block extra_breadcrumbs %}
&rsaquo; <a href="../">{{ page.path|escape }}</a>
&rsaquo; Copy
{% endblock %}

{% block content_title %}
<h1>Copy page: {{ page.path }}</h1>
{% endblock %}

{% block content %}
<fieldset class="module aligned">
  <h2>Original page data</h2>
  <div class="form-row">
    <label>Path:</label> {{ page.path }}
  </div>
  <div class="form-row">
    <label>State:</label> {{ page.get_state_display }}
  </div>
  <div class="form-row">
    <label>Language:</label> {{ page.path.get_locale_display }}
  </div>
  <div class="form-row">
    <label>Description:</label> {{ page.description }}
  </div>

  <h2>Template data</h2>
  <div class="form-row">
    <label>Name:</label> {{ page.tpl.NAME }}
  </div>
  <div class="form-row">
    <label>Description:</label> {{ page.tpl.DESCRIPTION }}
  </div>
</fieldset>

<fieldset class="module aligned">
  <h2>New copy data</h2>
  {% if perms.cms.add_page %}
  <form action="" method="post">{% csrf_token %}
    {% include "cms/form_fields.html" %}
    <a class="clone-link" href="#" onclick="javascript: id_path.value = '{{ page.path.id }}'; return false;">Same url (clone)</a>
  </form>
  {% else %}
  <p>Sorry, but you don't have permissions for this action</p>
  {% endif %}
</fieldset>
{% endblock %}

tcms/templates/cms/edit.html
{% extends "cms/cms_base.html" %}
{% load adminmedia static %}

{% block extra_title %}Edit page{% endblock %}

{% block extrastyle %}
<link href="{% admin_media_prefix %}css/changelists.css" rel="stylesheet" type="text/css" media="all" />
<link href="{% admin_media_prefix %}css/forms.css" rel="stylesheet" type="text/css" media="all" />
{# cms css files #}
<link href="{% get_static_prefix %}css/cms.css" rel="stylesheet" type="text/css" media="all" />
{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{% admin_media_prefix %}js/core.js"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/jquery.min.js"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/admin/RelatedObjectLookups.js"></script>
{# cms JS files #}
<script type="text/javascript" src="{% get_static_prefix %}js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/jquery.fancybox.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/cms.js"></script>
{% endblock %}

{% block extra_breadcrumbs %}
&rsaquo; {{ page.path|escape }}
{% endblock %}

{% block content_title %}
<h1>Edit page: {{ page.tpl.NAME }}</h1>
{% endblock %}

{% block content %}
{% block object-tools %}
<ul class="object-tools">
  <li><a href="{{ page.preview_url }}" target="_blank">Preview</a></li>
  {% if perms.cms.add_page %}
  <li><a href="copy/">Copy</a></li>
  {% endif %}
  <li><a href="export/">Export</a></li>
  {% if page.is_live %}
    {% if perms.cms.add_rendered and perms.cms.change_rendered %}
    <li><a href="refresh/">Refresh content</a></li>
    {% endif %}
    {% if perms.cms.change_page %}
    <li><a href="unpublish/">Unpublish</a></li>
    {% endif %}
  {% else %}
    {% if perms.cms.change_page and perms.cms.add_rendered and perms.cms.change_rendered %}
    <li><a href="publish/">Publish</a></li>
    {% endif %}
    {% if perms.cms.delete_page %}
    <li><a class="warning" href="delete/">Delete</a></li>
    {% endif %}
  {% endif %}
  <li><a href="../../{{ page.id }}/history/">History</a></li>
</ul>
{% endblock %}

<h3>Information</h3>
<fieldset class="module aligned">
  <form action="" method="post"{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>{% csrf_token %}
    <h2>Page data</h2>
    {% if perms.cms.change_page %}
    {% with form.page_fields as form %} {% include "cms/form_fields.html" %} {% endwith %}
    {% endif %}
    <div class="form-row">
      <label>Locale:</label> <strong>{{ page.path.get_locale_display }}</strong>
    </div>
    <div class="form-row">
      <label>State:</label> <strong>{{ state }}</strong>
    </div>
    <div class="form-row">
      <label>Updated:</label> {{ page.updated|date:"d M Y" }}
    </div>

    <div class="container">
      <h2 class="title collapsed">
        Metadata (<a id="link_metadata" class="collapse" href="#"><span class="label" style="display: none;">Hide</span><span class="label">Show</span></a>)
      </h2>
      <div id="container_metadata" style="display: none;">
        {% if perms.cms.change_page %}
          {% with form.metadata_fields as form %}
            {% include "cms/form_fields.html" %}
          {% endwith %}
        {% else %}
        <div class="form-row"><label>Title:</label> {{ page.meta_title|escape }}</div>
        <div class="form-row"><label>Description:</label> {{ page.meta_description|escape }}</div>
        <div class="form-row"><label>Keywerds:</label> {{ page.meta_keywords|escape }}</div>
        {% endif %}
      </div>
    </div>

    <div class="container">
      <h2 class="title collapsed">
        Search (<a id="link_search" class="collapse" href="#"><span class="label" style="display: none;">Hide</span><span class="label">Show</span></a>)
      </h2>
      <div id="container_search" style="display: none;">
        {% if perms.cms.change_page %}
          {% with form.search_fields as form %}
            {% include "cms/form_fields.html" %}
          {% endwith %}
        {% else %}
        <div class="form-row"><label>Text:</label> {{ page.search_text|escape }}</div>
        <div class="form-row"><label>Image:</label> {% if page.search_image %}<a href="{{ page.search_image.url }}" target="_blank">Preview</a>{% endif %}</div>
        {% endif %}
      </div>
    </div>
  </form>

  <div class="container">
    <h2 class="title collapsed">
      Template (<a id="link_tpl" class="collapse" href="#"><span class="label" style="display: none;">Hide</span><span class="label">Show</span></a>)
    </h2>
    <div id="container_tpl" style="display: none;">
      <div class="form-row">
        <label>Name:</label> {{ page.tpl.NAME }}
      </div>
      <div class="form-row">
        <label>Description:</label> {{ page.tpl.DESCRIPTION }}
      </div>
    </div>
  </div>
</fieldset>

<h3>Sections</h3>
<fieldset class="module aligned change-list" id="changelist">
  <h2>Page sections</h2>
  {% comment %}
  <form action="" method="post">{% csrf_token %}
    <div class="actions">
      Action:
      <select name="action">
        <option value="">---------</option>
        <option value="edit">{{ _("Edit") }}</option>
      </select>
      <input type="submit" value="{{ _("Go") }}" />
    </div>
  {% endcomment %}
    <table>
      <thead>
        <tr>
          {% comment %}
          <th class="action-checkbox-column">
            <input type="checkbox" id="toggler" />
          </th>
          {% endcomment %}
          <th>Name</th><th>Section</th><th>Description</th><th>Done</th>
          {% if perms.cms.add_value and perms.cms.change_value %}
          <th>Actions</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
      {% for name, section in page.tpl.iteritems %}
        <tr class="{% cycle "row1" "row2" %}">
          {% comment %}
          <td><input type="checkbox" name="section" value="{{ name|escape }}" /></td>
          {% endcomment %}
          <td>{{ name|title }}</td>
          <td>{{ section.NAME }}</td>
          <td>{{ section.DESCRIPTION }}</td>
          <td><span class="completed">{{ section.done_percent }}%</span></td>
          {% if perms.cms.add_value and perms.cms.change_value %}
          <td class="actions-links">
            <a title="Edit" href="{{ section.basename }}/"><img src="{% get_static_prefix %}img/edit.png" alt="Edit" /></a>
          </td>
          {% endif %}
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% comment %}
  </form>
  {% endcomment %}
</fieldset>
{% endblock %}

tcms/templates/cms/edit_section.html
{% extends "cms/cms_base.html" %}
{% load adminmedia cms_tags static %}

{% block extra_title %}Edit section{% endblock %}

{% block extrastyle %}
<link href="{% admin_media_prefix %}css/forms.css" rel="stylesheet" type="text/css" media="all" />
{# cms css files #}
<link href="{% get_static_prefix %}css/cms.css" rel="stylesheet" type="text/css" media="all" />
<link href="{% get_static_prefix %}css/fancybox.css" rel="stylesheet" type="text/css" media="all" />
{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{% admin_media_prefix %}js/core.js"></script>
<script type="text/javascript" src="{% url admin:jsi18n %}"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/jquery.min.js"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/calendar.js"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/admin/DateTimeShortcuts.js"></script>
{# cms JS files #}

{% if TCMS_CKEDITOR_BASE_URL %}
<script type="text/javascript" src="{{ TCMS_CKEDITOR_BASE_URL }}ckeditor.js"></script>
<script type="text/javascript" src="{{ TCMS_CKEDITOR_BASE_URL }}adapters/jquery.js"></script>
<script type="text/javascript">
    var ckeditorConfig = "{% get_static_prefix %}js/ckeditor_config.js";
</script>
<script type="text/javascript" src="{% get_static_prefix %}js/ckeditor_config.js"></script>
{% endif %}

<script type="text/javascript" src="{% get_static_prefix %}js/cms.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/jquery.form.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/jquery.fancybox.js"></script>
{% endblock %}

{% block extra_breadcrumbs %}
&rsaquo; <a href="../">{{ page.path|escape }}</a>
&rsaquo; {{ section_name|title }}
{% endblock %}

{% block content_title %}
<h1>Edit section: {{ section_name|title }}</h1>
{% endblock %}

{% block content %}
{% block object-tools %}
<ul class="object-tools">
  <li><a href="{{ page.preview_url }}" target="_blank">Preview</a></li>
  {% if perms.cms.add_page %}
  <li><a href="../copy/">Copy</a></li>
  {% endif %}
  <li><a href="../export/">Export</a></li>
  {% if page.is_live %}
    {% if perms.cms.add_rendered and perms.cms.change_rendered %}
    <li><a href="../refresh/">Refresh content</a></li>
    {% endif %}
    {% if perms.cms.change_page %}
    <li><a href="../unpublish/">Unpublish</a></li>
    {% endif %}
  {% else %}
    {% if perms.cms.change_page and perms.cms.add_rendered and perms.cms.change_rendered %}
    <li><a href="../publish/">Publish</a></li>
    {% endif %}
    {% if perms.cms.delete_page %}
    <li><a class="warning" href="../delete/">Delete</a></li>
    {% endif %}
  {% endif %}
  <li><a href="../../../{{ page.id }}/history/">History</a></li>
</ul>
{% endblock %}

<h3>Information</h3>
<fieldset class="module aligned">
  <div class="container">
    <h2 class="title collapsed">
      Page (<a id="link_page_info" class="collapse" href="#"><span class="label" style="display: none;">Hide</span><span class="label">Show</span></a>)
    </h2>
    <div id="container_page_info" style="display: none;">
      <div class="form-row">
        <label>URL:</label> {{ page.path }}
      </div>
      <div class="form-row">
        <label>State:</label> {{ state }}
      </div>
      <div class="form-row">
        <label>Updated:</label> {{ page.updated|date:"d M Y" }}
      </div>
    </div>
  </div>
</fieldset>

<fieldset class="module aligned">
  <div class="container">
    <h2 class="title">
      Section (<a id="link_section_info" class="collapse" href="#"><span class="label">Hide</span><span class="label" style="display: none;">Show</span></a>)
    </h2>
    <div id="container_section_info">
      <div class="form-row">
        <label>Name:</label> {{ section_name|title }}
      </div>
      <div class="form-row">
        <label>Section:</label> {{ section.NAME }}
      </div>
      <div class="form-row">
        <label>Description:</label> {{ section.DESCRIPTION }}
      </div>
      <div class="form-row">
        <label>Done:</label>
        <span class="completed">{{ section.done_percent }}%</span>
      </div>
    </div>
  </div>
</fieldset>

<h3>Section fragments</h3>
{% if perms.cms.add_value and perms.cms.change_value %}
{% for data in section.inc_form %}
  {% include data.tpl %}
{% endfor %}
{% else %}
<p>Sorry, but you don't have permissions for this action</p>
{% endif %}
{% endblock %}

tcms/templates/cms/form_fields.html
{% for field in form %}
  {% if not field.is_hidden %}
    <div class="form-row">
      {% if field.errors %}{{ field.errors }} {% else %}<ul class="errorlist" style="display: none;"></ul>{% endif %}
      <label{% if field.required %} class="required"{% endif %} for="{{ field.auto_id }}">{{ field.label }}:</label> {{ field }}
    </div>
  {% endif %}
{% endfor %}
{% for field in form %}
  {% if field.is_hidden %} {{ field }} {% endif %}
{% endfor %}
<div class="form-row">
    <input class="submit-button" type="submit" value="Save" />
    <span class="loading" style="display: none;">{{ _("Loading") }}</span>
    <span class="saved" style="display: none;"><span>{{ _("Saved") }}</span>
</div>

tcms/templates/cms/import.html
{% extends "cms/cms_base.html" %}
{% load adminmedia %}

{% block extra_title %}Import page{% endblock %}

{% block extrastyle %}
<link href="{% admin_media_prefix %}css/forms.css" rel="stylesheet" type="text/css" media="all" />
{% endblock %}

{% block extra_breadcrumbs %}
&rsaquo; Import
{% endblock %}

{% block content_title %}
<h1>Import page</h1>
{% endblock %}

{% block content %}
<fieldset class="module aligned">
  <h2>Import a page</h2>
  {% if perms.cms.add_path and perms.cms.add_page and perms.cms.add_value %}
  <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {% include "cms/form_fields.html" %}
  </form>
  {% else %}
  <p>Sorry, but you don't have permissions for this action</p>
  {% endif %}
</fieldset>
{% endblock %}

tcms/templates/cms/page_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n adminmedia admin_list cms_tags static %}

{% block extrastyle %}
{{ block.super }}
<link href="{% get_static_prefix %}css/cms.css" rel="stylesheet" type="text/css" media="all" />
{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{% admin_media_prefix %}js/jquery.min.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/cms.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/jquery.form.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}js/jquery.fancybox.js"></script>
{% endblock %}


{% block object-tools %}
{% if has_add_permission %}
  <ul class="object-tools">
    {% if perms.cms.add_path and perms.cms.add_page and perms.cms.add_value %}
    <li><a href="import/{% if is_popup %}?_popup=1{% endif %}" class="addlink">Import</a></li>
    {% endif %}
    <li>
      <a href="add/{% if is_popup %}?_popup=1{% endif %}" class="addlink">
        {% blocktrans with cl.opts.verbose_name as name %}Add {{ name }}{% endblocktrans %}
      </a>
    </li>
  </ul>
{% endif %}
{% endblock %}

{% block filters %}
{% if cl.has_filters %}
<div id="changelist-filter">
  <h2>{% trans 'Filter' %}</h2>
  {% for spec in cl.filter_specs %}
     {% admin_list_filter cl spec %}
  {% endfor %}
  {% if locale_filter %}
    {% admin_list_filter cl locale_filter %}
  {% endif%}
  {% admin_template_filter cl template_filter %}
</div>
{% endif %}
{% endblock %}

tcms/templates/cms/page_history.html
{% extends "admin/object_history.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="../../../../">Home</a>
  &rsaquo; <a href="../../../">{% trans 'Cms' %}</a>
  &rsaquo; <a href="../../">{% trans 'Pages' %}</a>
  &rsaquo; <a href="../../p/{{ object.id }}/">{{ object.path|escape }}</a>
  &rsaquo; {% trans 'History' %}
</div>
{% endblock %}

tcms/templates/cms/template_filter.html
{% load i18n %}
<h3>{% blocktrans with title as filter_title %} By {{ filter_title }} {% endblocktrans %}</h3>
<ul>
{% for name, items in choices %}
  {% if forloop.first %}
    <li{% if items.0.selected %} class="selected"{% endif %}><a href="{{ items.0.query_string|iriencode }}">{{ items.0.display }}</a></li>
  {% else %}
    <li>
      <strong>{{ name|title }}</strong>
      <ul>
      {% for choice in items %}
        <li{% if choice.selected %} class="selected"{% endif %}>
          <a href="{{ choice.query_string|iriencode }}">{{ choice.display }}</a>
        </li>
      {% endfor %}
      </ul>
    </li>
  {% endif %}
{% endfor %}
</ul>